### ISSUE TITLE
The addon don't work with Blender 4.0

### ISSUE THREAD

**Issue by lynecourtois** [jayanam/shortcut_VUr#34]
Hello !
I have changed my blender version to 4.0 and it doesn't work any more. It gives me this error : 
![Capture d'écran 2023-11-21 094321](https://github.com/jayanam/shortcut_VUr/assets/58252102/d72769c1-f5ca-41c1-bf3a-f13f09c16981)

Thanks in advance for your help!

**Comment by ryankingart** [comment]
Hello. This is happening to me as well. The addon doesn't work in Blender 4.0. If this can be fixed, I'd really appreciate it. Thanks!

**Comment by catafest** [comment]
nothing, tested and not work on version 4.1 ... 
maybe he should archive this project and switch it to discontinued ... 

`Python: Traceback (most recent call last):
  File "C:\Users\catafest\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\shortcut_VUr-master\scv_op.py", line 54, in invoke
    self.draw_util.create_batches(context, self.mouse_input)
  File "C:\Users\catafest\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\shortcut_VUr-master\scv_draw_util.py", line 44, in create_batches
    self.shader = gpu.shader.from_builtin('2D_UNIFORM_COLOR')
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '2D_UNIFORM_COLOR'
`

**Comment by gchriz** [comment]
I fixed it to work in Blender 4.0.
Please see my pull request: https://github.com/jayanam/shortcut_VUr/pull/35

Until it's merged in here you might want to try my fork: https://github.com/gchriz/shortcut_VUr

**Comment by BlenderInferno** [comment]
Thank you gchriz!

**Comment by laurazag** [comment]
> I fixed it to work in Blender 4.0. Please see my pull request: #35
> 
> Until it's merged in here you might want to try my fork: https://github.com/gchriz/shortcut_VUr

For some reason, i install and give me an error.
![image](https://github.com/jayanam/shortcut_VUr/assets/20033886/3f2b20a6-9be1-4531-8fce-65ca27de5076)

**Comment by gchriz** [comment]
> For some reason, i install and give me an error.
> ![image](https://github.com/jayanam/shortcut_VUr/assets/20033886/3f2b20a6-9be1-4531-8fce-65ca27de5076)

It looks like you installed the original version. My fix - contained in
pull request #35 - in not yet included.

Since I don't know when yayanam will merge it - if ever - I cloned this
original repository into my own here:

https://github.com/gchriz/shortcut_VUr

There my fix is included.
Please try to install that one and let me know if it works.

**Comment by laurazag** [comment]
But I downloaded your version and I still have this problem, because this version of yours was made on the 1st of this month. As shown in the screenshots below:
![image](https://github.com/jayanam/shortcut_VUr/assets/20033886/55807ded-eddc-4473-84bf-8607d8dc0071)
![image](https://github.com/jayanam/shortcut_VUr/assets/20033886/c1c17554-9faf-4135-af85-f20fbf9069ad)
And it still kept generating errors :(

**Comment by gchriz** [comment]
Yes, the files in your screenshot seem to be the right ones. Which exact version of Blender are you using?

**Comment by LauraZaguini** [comment]
> Yes, the files in your screenshot seem to be the right ones. Which exact version of Blender are you using?

I'm using version 4.0, which is the latest version. I downloaded your version that improved it, but it continues to have this problem. Very strange

**Comment by LauraZaguini** [comment]
Well, that doesn't change much, especially because I downloaded it from the official Blender website.

**Comment by laurazag** [comment]
Okay, now it works. Basically I threw the files inside it into the addons folder in scripts instead of installing the .zip directly from the Blender panel. For some reason this worked...

**Comment by gchriz** [comment]
That's fine!

**Comment by gchriz** [comment]
It seems one need to restart Blender after installing the fixed version **over the original one**. 
Otherwise the old version remains in Blenders memory and still fails.

Worth reading: https://blender.stackexchange.com/questions/2691/is-there-a-way-to-restart-a-modified-addon#2692

**Comment by hopezh** [comment]
I tried to add the unzipped folder directly into `C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons`, but it still produces the following error: 

![2024-02-15 13 49 20](https://github.com/jayanam/shortcut_VUr/assets/23435810/b94207ca-48ff-403f-b13f-e3a89228ed4c)

**Comment by gchriz** [comment]
Did you really use the fixed version (https://github.com/gchriz/shortcut_VUr)?
And did you restart Blender after installing it?

**Comment by hopezh** [comment]
> Did you really use the fixed version (https://github.com/gchriz/shortcut_VUr)? And did you restart Blender after installing it?

Yes, the fixed version works well after installing from add-ons. Thanks.

**Comment by Rus-Abd** [comment]
> Did you really use the fixed version (https://github.com/gchriz/shortcut_VUr)? And did you restart Blender after installing it?

This worked for me,

**Comment by christian66-gif** [comment]
Hello... Works correctly in Blender 4.2.0 and in UpBGE 0.42.0 ... with the correction of gchriz .

-  also works with Blender 4.3.0  
many thanks ;)

**Comment by rickygai** [comment]
Blender 4.1.1
Shortcut VUr by Jayanam 0.9.2.0

It is confirmed after installed the fixed version, **you have to restart Blender** then there is no Python error messages anymore.

Thanks again.

**Comment by Elucidation** [comment]
Thanks @gchriz your fork works for me with the current Blender 4.0
